#!/usr/bin/env python3

import roslib
roslib.load_manifest("edge_tpu")
import sys
import rospy
import cv2
import time
from std_msgs.msg import String
from sensor_msgs.msg import Image, CompressedImage
from vision_msgs.msg import Detection2DArray, Detection2D, BoundingBox2D, ObjectHypothesisWithPose
from cv_bridge import CvBridge, CvBridgeError
import numpy as np
import PIL

import edgetpu.detection.engine

class tpu_detector:

    def __init__(self, model, labels, threshold=0.5, device_path=None, compressed=False):
        self.bridge = CvBridge()
        rospy.loginfo("Loading model {}".format(model))

        self.compressed = compressed

        if self.compressed:
            self.image_sub = rospy.Subscriber("input", CompressedImage, self.callback, queue_size=1)
        else:
            self.image_sub = rospy.Subscriber("input", Image, self.callback, queue_size=1)

        self.threshold = threshold
        self.engine = edgetpu.detection.engine.DetectionEngine(model, device_path)
        rospy.loginfo("Engine loaded")
        self.load_labels(labels)
        self.detection_pub = rospy.Publisher('detections', Detection2DArray, queue_size=1)

    def load_labels(self, labels):
        with open(labels, 'r', encoding="utf-8") as f:
            pairs = (l.strip().split(maxsplit=1) for l in f.readlines())
            self.labels = dict((int(k), v) for k, v in pairs)

    def callback(self,data):
        try:
            if self.compressed:
                np_image = np.frombuffer(data.data, dtype=np.uint8)
                cv_image = cv2.imdecode(np_image, cv2.IMREAD_UNCHANGED)
            else:
                cv_image = self.bridge.imgmsg_to_cv2(data, desired_encoding="passthrough")
        except CvBridgeError as e:
            rospy.logerr(e)

        results = self.engine.DetectWithImage(PIL.Image.fromarray(cv_image), top_k=1, threshold=self.threshold, keep_aspect_ratio=True, relative_coord=True)
        
        detections = Detection2DArray()
        now = rospy.get_rostime()

        for detection in results:
        
            top_left, bottom_right = detection.bounding_box
            min_x, min_y = top_left
            max_x, max_y = bottom_right
            
            imheight, imwidth, _ = cv_image.shape
            
            min_x *= imwidth
            max_x *= imwidth
            min_y *= imheight
            max_y *= imheight
            
            centre_x = (max_x+min_x)/2.0
            centre_y = (max_y+min_y)/2.0
            height = max_y-min_y
            width = max_x-min_x
            
            if height <=0 or width <= 0:
              continue
            
            bbox = BoundingBox2D()
            bbox.center.x = centre_x
            bbox.center.y = centre_y
            bbox.size_x = width
            bbox.size_y = height
            
            hypothesis = ObjectHypothesisWithPose()
            hypothesis.id = detection.label_id
            hypothesis.score = detection.score
            hypothesis.pose.pose.position.x = centre_x
            hypothesis.pose.pose.position.y = centre_y

            crop = cv_image[int(min_y):int(max_y), int(min_x):int(max_x)].astype('uint8')
            #crop_msg = self.bridge.cv2_to_imgmsg(crop, encoding="rgb8")

            res, buffer = cv2.imencode(".png", crop)

            instance = Detection2D()
            instance.header.stamp = now
            instance.header.frame_id = data.header.frame_id
            instance.results.append(hypothesis)
            instance.bbox = bbox
            instance.source_img_compressed.data = np.array(buffer).tostring()
            instance.source_img_compressed.header.frame_id = data.header.frame_id
            instance.source_img_compressed.header.stamp = now

            detections.detections.append(instance)

            rospy.loginfo("Detected: {}".format(detection.label_id))
            
        if len(results) > 0:
            self.detection_pub.publish(detections)
        
        rospy.logdebug("%.2f ms" % self.engine.get_inference_time())

def main(args):

    rospy.init_node('detect', anonymous=True)
    
    model_path = rospy.get_param('~model_path')
    label_path = rospy.get_param('~label_path')
    compressed = rospy.get_param('~compressed')
    threshold = rospy.get_param('~threshold', default=0.5)
    device_path = rospy.get_param('~device_path', default=None)

    detector = tpu_detector(model_path, label_path, threshold, device_path, compressed)

    try:
        rospy.spin()
    except KeyboardInterrupt:
        print("Shutting down")

if __name__ == "__main__":
    main(sys.argv)
